USE prouni2016;
 
LOAD DATA LOCAL INFILE '~/Desktop/amostra_pda_prouni_2016.csv'
INTO TABLE prouni_tabelao
CHARACTER SET latin1         
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'	
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(  
    ANO_CONCESSAO_BOLSA,
    CODIGO_EMEC_IES_BOLSA,
    NOME_IES_BOLSA,TIPO_BOLSA,
    MODALIDADE_ENSINO_BOLSA,
    NOME_CURSO_BOLSA,
    NOME_TURNO_CURSO_BOLSA,
    CPF_BENEFICIARIO_BOLSA,
    SEXO_BENEFICIARIO_BOLSA,
    RACA_BENEFICIARIO_BOLSA,
    @DT_NASCIMENTO_BENEFICIARIO,
    BENEFICIARIO_DEFICIENTE_FISICO,
    REGIAO_BENEFICIARIO_BOLSA,
    SIGLA_UF_BENEFICIARIO_BOLSA,
    MUNICIPIO_BENEFICIARIO_BOLSA
)
SET dt_nascimento_beneficiario = STR_TO_DATE(@DT_NASCIMENTO_BENEFICIARIO, '%d-%m-%Y');
-- dt_nascimento_beneficiario = coluna tipo date da tabela prouniTabelao

-- SET dt_nascimento_beneficiario = STR_TO_DATE(@DT_NASCIMENTO_BENEFICIARIO, '%d-%m-%Y');
-- beneficiario_deficiente_fisico = IF (@BENEFICIARIO_DEFICIENTE_FISICO = 'SIM', 'S', 'N');
